I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/custom system.rpy", line 240, in script call
    call screen makeplayerUI(roommanager)
  File "game/custom system.rpy", line 231, in script
    $inventory.activeitem.interpretdrop(dropn,roommanager)
  File "game/custom system.rpy", line 231, in <module>
    $inventory.activeitem.interpretdrop(dropn,roommanager)
  File "game/custom system.rpy", line 186, in interpretdrop
    renpy.jump(self.solutionlabs[solnum])
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/custom system.rpy", line 240, in script call
    call screen makeplayerUI(roommanager)
  File "game/custom system.rpy", line 231, in script
    $inventory.activeitem.interpretdrop(dropn,roommanager)
  File "C:\Users\Admin\Desktop\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Admin\Desktop\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/custom system.rpy", line 231, in <module>
    $inventory.activeitem.interpretdrop(dropn,roommanager)
  File "game/custom system.rpy", line 186, in interpretdrop
    renpy.jump(self.solutionlabs[solnum])
  File "C:\Users\Admin\Desktop\Renpy\renpy-8.0.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Space Breakers 0.1
Sun Apr  2 02:41:51 2023
