I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 326, in script
    play sound hyrauliclong volume 0.6
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 326, in <module>
    play sound hyrauliclong volume 0.6
NameError: name 'hyrauliclong' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 326, in script
    play sound hyrauliclong volume 0.6
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 326, in <module>
    play sound hyrauliclong volume 0.6
NameError: name 'hyrauliclong' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Space Breakers 0.1
Sun Mar 26 22:19:34 2023
